### PR TITLE
Add the EAD attack to torchattacks and bug fix

### PR DESCRIPTION
**Pull request by rikonaka**
## PR Type and Checklist
What kind of change does this PR introduce?

- [x] FIX BUG
	- [x] Fix bug in issues https://github.com/Harry24k/adversarial-attacks-pytorch/issues/136, call the `_check_inputs` and `_check_outputs` (also normalize) function in class `Attack`'s `__call__` function instead of every forward function (also remove all from forward function) in https://github.com/Harry24k/adversarial-attacks-pytorch/pull/137/commits/5fe65ec2fe01b8a57699d2cfb952d4dc02c2394f.
	- [x] `DeepFool` attack has one line bug in [here](https://github.com/Harry24k/adversarial-attacks-pytorch/blob/9a22433760c665e816ef2cd96fd3515e59b06b19/torchattacks/attacks/deepfool.py#L92), in fact, the value of `label` could be 9 but the length of `value` only 8 on CIFAR10, we don't need to get all non-label values from the jacobian matrix, `fs-fs[label]` will make the label row become 0, and set label row `inf` next then pick min value is not affect. I also modified deepfool's main loop to make the code lean and easy to read in https://github.com/Harry24k/adversarial-attacks-pytorch/pull/137/commits/9801db87f51ef225a0b8438132e7e044ac3481a5.
- [x] ADD ATTACK
	- [x] Add the EADL1 attack in https://github.com/Harry24k/adversarial-attacks-pytorch/pull/137/commits/51aafef265c8b7fe4ebfd6729b5bc1b549ae82ae.
	- [x] Add the EADEN (L1+L2) attack in https://github.com/Harry24k/adversarial-attacks-pytorch/pull/137/commits/51aafef265c8b7fe4ebfd6729b5bc1b549ae82ae.
- [x] Other... Please describe:
	- [x] Fix `JSMA` and `SPSA` parameters describe.
	- [x] Fix `UPGD` attack `one_hot_labels`  error (same as previous `CW` bug).
	- [x] Some format change (use autopep8).
	- [x] Init `normalization_used` and `_normalization_applied` in `__init__` function.
	- [x] Fix `get_logits` function how to check `_normalization_applied`.

### CODE REVIEW

**Comment by rikonaka** [comment]
On 64 CIFAR10 test datasets, the EADL1 untargeted attack reduces accuracy to 1.56%, and the EADEN untargeted attack reduces accuracy also to 1.56%, but I did not see any target attack method in paper.

image

The value $t_0$ is not used in the Algorithm 1...but I still supported targeted attack in code, even though the accuracy rate would only drop to 64%. 🤨

**Comment by Harry24k** [comment]
I'm surprised that you were already fixed the normalization part 😄. 
The current validation check process has some issues when we use `normalized_used=True`, 
such as `ValueError: Input must have a range [0, 1] (max: 1.0, min: -2.9802322387695312e-08)`.
I'm working on it.

BTW, there is an error during the coverage check. Could you fix the problem? :
```
code_coverage/test_atks.py::test_atks_on_cifar10[OnePixel]
  /home/runner/work/adversarial-attacks-pytorch/adversarial-attacks-pytorch/torchattacks/attacks/_differential_evolution.py:592: RuntimeWarning: divide by zero encountered in double_scalars
    convergence=self.tol / convergence) is True):
```

**Comment by rikonaka** [comment]
Hi @Harry24k , but I did not found the same error when I run `OnePixel` attack 😂.

It's looks like an error in the `_differential_evolution.py` file not `OnePixel`.

image

**Comment by rikonaka** [comment]
Hi @Harry24k , I found the problem, in the [line](https://github.com/Harry24k/adversarial-attacks-pytorch/blob/5ef15ea6a8f26696409f07e9e819b1dc1b57fde0/torchattacks/attacks/_differential_evolution.py#L592) of `_differential_evolution.py`, the value of `convergence` could be 0 when run the `OnePixel` attack.

I modified the code so that the value is set to `inf` when it is divided by 0.

image

**Pull request merged**
